<?php
return array(
    'database'=>array(
        'host'=>'127.0.0.1',//默认主机
        'port'=>3306,//默认端口号
        'dbname'=>'data',//默认数据库
        'charset'=>'utf8',//默认字符编码集
        'user'=>'root',//默认数据库的用户
        'pwd'=>'3459',//默认数据库的密码
        'dbtype'=>'mysql',//默认数据库的类型
    ),
    'app'=>array(
        'dp'=>'Admin',//默认平台
        'dc'=>'User',//默认控制器
        'dm'=>'Login',//默认方法
        'dk'=>'',//加密密钥
        'path'=>'./Public/Upload',//默认文件上传路径
        'size'=>72345,//默认上传文件大小
        'ftype'=>['image/jpeg','image/png','image/gif'],//默认文件上传类型
    )
);
